name: CI_DEPLOY

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: TodoList
      env:
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        set -eu
        echo "Deploying blog files"
        SSHPATH="$HOME/.ssh"
        mkdir "$SSHPATH"
        echo "$KEY" > "$SSHPATH/key" && chmod 400 "$SSHPATH/key"
        SERVER_DEPLOY_PATH="adrian@handigital.rbacher.fr:/var/www/html/adrian"
        sh -c "rsync -arv --delete -e 'ssh -o StrictHostKeyChecking=no -i $SSHPATH/key -p 22' $GITHUB_WORKSPACE/ $SERVER_DEPLOY_PATH"
